[tools]
ruby = "4.0.6"
"gem:tmuxinator" = "3"
node = "24.19.0"
"npm:@kilocode/cli" = "7"
pipx = "1.16.7"
uv = "0.12.5"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
